# Generated by Django 5.1.1 on 2024-09-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
