# Generated by Django 5.1.1 on 2024-09-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_alter_book_image_url_alter_book_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
